force-app/main/default/objects/Opportunity/fields/Best_Sales_Agent__c.field-meta.xml
<CustomField>
    <fullName>Best_Sales_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Sales agent who got the most Completed tours (this agent will receive some compensation)</inlineHelpText>
    <label>Best Sales Agent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Completed_Tours__c.field-meta.xml
<CustomField>
    <fullName>Completed_Tours__c</fullName>
    <label>Completed Tours</label>
    <summaryFilterItems>
        <field>Tour__c.Completed_on__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>Tour__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Discount_Offered__c.field-meta.xml
<CustomField>
    <fullName>Discount_Offered__c</fullName>
    <inlineHelpText>Discount offered on the Completed Tour</inlineHelpText>
    <label>Discount offered</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tour__c/Tour__c.object-meta.xml
<CustomObject>
    <label>Tour</label>
    <nameField>
        <displayFormat>TOUR-{000}</displayFormat>
        <label>Tour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tour__c/fields/Completed_Goals__c.field-meta.xml
<CustomField>
    <fullName>Completed_Goals__c</fullName>
    <label>Completed Goals</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tour completed</fullName>
            </value>
            <value>
                <fullName>Proposal Generated</fullName>
            </value>
            <value>
                <fullName>Client commitment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tour__c/fields/Completed_on__c.field-meta.xml
<CustomField>
    <fullName>Completed_on__c</fullName>
    <label>Completed on</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tour__c/fields/Discount_Offered__c.field-meta.xml
<CustomField>
    <fullName>Discount_Offered__c</fullName>
    <label>Discount Offered</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tour__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Tours</relationshipLabel>
    <relationshipName>Tours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tour__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TourTriggerHelperTest.cls
@isTest
public with sharing class TourTriggerHelperTest {
    @TestSetup
    static void setup() {
        UserRole northEastRole = [SELECT Id FROM UserRole WHERE Name = 'Sales North-East Agent'];
        User northAgent = DataFactory.createUser('Sales Agent Profile', 'NorthAgent');
        northAgent.UserRoleId = northEastRole.Id;
        insert northAgent;

        System.runAs(northAgent) {
            Account account = DataFactory.createAccount('Client X');
            insert account;

            Opportunity opportunity = DataFactory.createOpportunity(account.Id);
            insert opportunity;

            Tour__c tour = DataFactory.createTour(opportunity.Id, northAgent.Id);
            insert tour;
        }
    }

    @isTest
    public static void whenUpdateATourToCompletedThenUpdateItAndRelatedOpportunity() {
        List<Tour__c> toursToUpdate = [SELECT Id, Opportunity__c FROM Tour__c WHERE Completed_on__c = null];
        User user = [SELECT Id FROM User WHERE UserName = 'NorthAgent@testorg.com'];
        Test.startTest();
        System.runAs(user) {
            for (Tour__c tourToUpdate : toursToUpdate) {
                tourToUpdate.Completed_Goals__c = Constants.TOUR_CG_TOUR_COMPLETED;
            }
            update toursToUpdate;
        }
        Test.stopTest();
        Opportunity opportunityUpdated = [SELECT Id, Completed_Tours__c, Best_Sales_Agent__c, (SELECT Id, Status__c, Completed_On__c FROM Tours__r WHERE Id = :toursToUpdate[0].Id) FROM Opportunity WHERE Id = :toursToUpdate[0].Opportunity__c];
        System.assert(opportunityUpdated.Completed_Tours__c > 0);
        System.assert(opportunityUpdated.Best_Sales_Agent__c != null);
        System.assert(opportunityUpdated.Tours__r[0].Completed_On__c != null);
        System.assertEquals(Constants.TOUR_STATUS_COMPLETED,opportunityUpdated.Tours__r[0].Status__c, 'Tour was not marked as Completed');
    }

    @isTest
    public static void whenUpdateATourToProposalGeneratesThenUpdateRelatedOpportunity() {
        List<Tour__c> toursToUpdate = [SELECT Id, Opportunity__c FROM Tour__c WHERE Completed_on__c = null];

        Opportunity opportunityToSetAsCompleted = [SELECT Id FROM Opportunity WHERE Id = :toursToUpdate[0].Opportunity__c];
        opportunityToSetAsCompleted.StageName = Constants.OPPORTUNITY_STAGE_TOUR_COMPLETED;
        update opportunityToSetAsCompleted;

        User user = [SELECT Id FROM User WHERE UserName = 'NorthAgent@testorg.com'];
        Test.startTest();
        System.runAs(user) {
            for (Tour__c tourToUpdate : toursToUpdate) {
                tourToUpdate.Completed_Goals__c = Constants.TOUR_CG_PROPOSAL_GENERATED;
                tourToUpdate.Discount_Offered__c = 0.1;
                tourToUpdate.Proposal_Value__c = 1000;
            }
            update toursToUpdate;
        }
        Test.stopTest();
        Opportunity opportunityUpdated = [SELECT Id, StageName, Amount, Discount_Offered__c, Completed_Tours__c, Best_Sales_Agent__c, (SELECT Id, Status__c, Completed_On__c FROM Tours__r WHERE Id = :toursToUpdate[0].Id) FROM Opportunity WHERE Id = :toursToUpdate[0].Opportunity__c];
        System.assertEquals(Constants.OPPORTUNITY_STAGE_READY_COMMITMENT, opportunityUpdated.StageName, 'Opportinity was not updated to Ready for Commitment');
        System.assert(opportunityUpdated.Amount == 1000);
        System.assert(opportunityUpdated.Discount_Offered__c == 0.1);
        System.assert(opportunityUpdated.Completed_Tours__c > 0);
        System.assert(opportunityUpdated.Best_Sales_Agent__c != null);
        System.assert(opportunityUpdated.Tours__r[0].Completed_On__c != null);
        System.assertEquals(Constants.TOUR_STATUS_COMPLETED,opportunityUpdated.Tours__r[0].Status__c, 'Tour was not marked as Completed');
    }
}