force-app/main/default/objects/Opportunity/fields/Discount_Offered__c.field-meta.xml
<CustomField>
    <fullName>Discount_Offered__c</fullName>
    <inlineHelpText>Discount offered on the Completed Tour</inlineHelpText>
    <label>Discount offered</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tour__c/Tour__c.object-meta.xml
<CustomObject>
    <label>Tour</label>
    <nameField>
        <displayFormat>TOUR-{000}</displayFormat>
        <label>Tour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tour__c/fields/Agent_Attribution__c.field-meta.xml
<CustomField>
    <fullName>Agent_Attribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To know which agent completed the tour (can be different from the Owner of the tour and must always related to a Sales agent using the user’s role)</description>
    <inlineHelpText>The agent who completed the tour</inlineHelpText>
    <label>Agent Attribution</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Tours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tour__c/fields/Completed_Goals__c.field-meta.xml
<CustomField>
    <fullName>Completed_Goals__c</fullName>
    <label>Completed Goals</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tour completed</fullName>
            </value>
            <value>
                <fullName>Proposal Generated</fullName>
            </value>
            <value>
                <fullName>Client commitment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tour__c/fields/Completed_on__c.field-meta.xml
<CustomField>
    <fullName>Completed_on__c</fullName>
    <label>Completed on</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tour__c/fields/Discount_Offered__c.field-meta.xml
<CustomField>
    <fullName>Discount_Offered__c</fullName>
    <label>Discount Offered</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tour__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Tours</relationshipLabel>
    <relationshipName>Tours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TourTriggerHelper.cls
public with sharing class TourTriggerHelper {
    public static void selfUpdate(List<Tour__c> tours, Map<Id, Tour__c> oldToursIndexedById ) {
        for (Tour__c tour : tours) {
            if (
                oldToursIndexedById.get(tour.Id).Completed_Goals__c != tour.Completed_Goals__c
                &&
                tour.Completed_Goals__c == Constants.TOUR_CG_TOUR_COMPLETED
            ) {
                tour.Completed_On__c = Datetime.now();
            }
        }
    }
    public static void opportunityRelatedUpdate(List<Tour__c> tours, Map<Id, Tour__c> oldToursIndexedById ) {
        for (Tour__c tour : tours) {
            relatedOpportunitiesIdsSet.add(tour.Opportunity__c);
        }
        Map<Id, Opportunity> opportunitiesIndexedById = [SELECT Id FROM Opportunity WHERE Id IN :relatedOpportunitiesIdsSet WITH USER_MODE FOR UPDATE];
        // Set<Id> relatedOpportunitiesIdsSet = new Set<Id>();
        // Map<Id, List<Tour__c>> toursIndexedByOpportunityId = new Map<Id, List<Tour__c>>();
        // for (Tour__c tour : tours) {
        //     relatedOpportunitiesIdsSet.add(tour.Opportunity__c);
        //     if (toursIndexedByOpportunityId.keySet().contains(tour.Opportunity__c)) {
        //         toursIndexedByOpportunityId.get(tour.Opportunity__c).add(tour);
        //     } else {
        //         toursIndexedByOpportunityId.put(tour.Opportunity__c, new List<Tour__c>{tour});
        //     }
        // }
        // List<Opportunity> relatedOpportunities = [SELECT Id FROM Opportunity WHERE Id IN :relatedOpportunitiesIdsSet WITH USER_MODE FOR UPDATE];

        // //Find the agent with more completed tour per opportunity, without persist data
        // List<AggregateResult> groupedResults = [SELECT COUNT(Id) tours, Agent_Attribution__c agent, Opportunity__c opportunity FROM Tour__c WHERE Completed_on__c != null GROUP BY Opportunity__c, Agent_Attribution__c ORDER BY COUNT(Id) DESC];
        // for (AggregateResult ar : groupedResults) {
        //     Id salesAgent = ar.get('agent');
        // }

        // Map<Id, List<Opportunity>> opportunitiesIndexedByTourId = new Map<Id, List<Opportunity>>();
        // for (Opportunity opportunity : relatedOpportunities) {

        // }
        for (Tour__c tour : tours) {
            Opportunity relatedOpportunity = opportunitiesIndexedById.get(tour.Opportunity__c);
            if (
                oldToursIndexedById.get(tour.Id).Completed_Goals__c != tour.Completed_Goals__c
                &&
                tour.Completed_Goals__c == Constants.TOUR_CG_PROPOSAL_GENERATED
            ) {
                relatedOpportunity.Discount_Offered__c = tour.Discount_Offered__c;
                opportunitiesIndexedById.put(tour.Opportunity__c, relatedOpportunity);
            }
        }
        Database.update(opportunitiesIndexedById.values(), true, AccessLevel.USER_MODE);
    }
}