force-app/main/default/objects/Tour__c/Tour__c.object-meta.xml
<CustomObject>
    <label>Tour</label>
    <nameField>
        <displayFormat>TOUR-{000}</displayFormat>
        <label>Tour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tour__c/fields/Agent_Attribution__c.field-meta.xml
<CustomField>
    <fullName>Agent_Attribution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To know which agent completed the tour (can be different from the Owner of the tour and must always related to a Sales agent using the user’s role)</description>
    <inlineHelpText>The agent who completed the tour</inlineHelpText>
    <label>Agent Attribution</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Agent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Tours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tour__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Tours</relationshipLabel>
    <relationshipName>Tours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tour__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataFactory.cls
public with sharing class DataFactory {
    public static User createUser(String aProfileName, String aName) {
        Profile lProfile = [SELECT Id FROM Profile WHERE Name = :aProfileName];
        return new User(
        Alias = aName.left(8),
        Email = aName + '@testorg.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'Testing',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        ProfileId = lProfile.Id,
        TimeZoneSidKey = 'America/Los_Angeles',
        UserName = aName + '@testorg.com'
        );
    }
    public static Account createAccount(String aName) {
        return new Account(
        Name = aName
        );
    }
    public static Opportunity createOpportunity(Id accountId) {
        return new Opportunity(
        StageName = Constants.OPPORTUNITY_STAGE_NEW,
        Name = 'Test Opportunity',
        CloseDate = Date.Today(),
        AccountId = accountId
        );
    }
    public static Tour__c createTour(Id opportunityId, Id agentId) {
        return new Tour__c(
        Opportunity__c = opportunityId,
        Agent_Attribution__c = agentId,
        Status__c = Constants.TOUR_STATUS_ACTIVE
        );
    }
}